# syntax=docker/dockerfile:1

FROM golang:1.17-alpine3.15

COPY go.mod ./
COPY go.sum ./
ADD static ./static
ADD templates ./templates

RUN go mod download

COPY *.go ./

RUN go build -o /web-starter-app
RUN go mod vendor

EXPOSE 5000

CMD [ "/golang_app" ]